### Rota para pegar os produtos
GET http://localhost:3000/produtos

### fechando a requicisao

### Rota criando o produto
POST http://localhost:3000/produtos
Content-Type: application/json

{
    
    "nome":"GTX 5090 24gb",
    "preco":19999,
    "quantidade": 12
}

###

### Pegar produto por ID
GET http://localhost:3000/produtos/3
Content-Type: application/json

###

### PUT - Editar produtos
PUT http://localhost:3000/produtos/3
Content-Type: application/json

{
    "novoNome": "GTX 3070 16gb",
    "novoPreco": 12000,
    "novaQuantidade": 10
}

###

### DELETE - Deletar produto
DELETE http://localhost:3000/produtos/1
Content-Type: application/json

###

### - DELETE - Excluindo todos os produtos
DELETE http://localhost:3000/produtos
Content-Type: application/json

###